version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-latest
      - build-1.16
      - build-1.15
  scheduled:
    triggers:
      - schedule:
          cron: "1 2 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-latest
      - build-1.16
      - build-1.15

jobs:
  build-latest: &build-template
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout
      - run: uname -a
      - run: go version
      - run: go vet ./...
      - run:
          name: golint
          command: |
                    go get -u golang.org/x/lint/golint
                    golint -set_exit_status ./...
      - run:
          name: staticcheck.io
          command: |
                    go get honnef.co/go/tools/cmd/staticcheck
                    staticcheck -checks all ./...
      - run:
          name: Check gofumpt formatting
          command: |
                    go get mvdan.cc/gofumpt
                    gofumpt -d .
                    [ -z "$(gofumpt -l .)" ]
      - run: go build
      - run:
          name: Test diff
          command: |
                    for x in a b c d e f g ; do
                      for y in a b c d e f g ; do
                        ./ip_diff test/$x.txt test/$y.txt > got.txt
                        diff -Naur test/${x}_${y}_diff.txt got.txt
                        rm got.txt
                      done
                    done

  build-1.16:
    <<: *build-template
    docker:
      - image: circleci/golang:1.16

  build-1.15:
    <<: *build-template
    docker:
      - image: circleci/golang:1.16
