version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-1.21
      - build-1.20
  scheduled:
    triggers:
      - schedule:
          cron: "1 2 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-1.21
      - build-1.20

jobs:
  build-latest: &build-template
    docker:
      - image: cimg/go

    steps:
      - checkout
      - run: uname -a
      - run: go version
      - run: go vet ./...
      - run:
          name: golint
          command: |
                    go install golang.org/x/lint/golint@latest
                    golint -set_exit_status ./...
      - run:
          name: staticcheck.io
          command: |
                    go install honnef.co/go/tools/cmd/staticcheck@latest
                    staticcheck -checks all ./...
      - run:
          name: Check gofumpt formatting
          command: |
                    go install mvdan.cc/gofumpt@latest
                    gofumpt -d .
                    [ -z "$(gofumpt -l .)" ]
      - run: go build
      - run:
          name: Test diff
          command: |
                    for x in a b c d e f g ; do
                      for y in a b c d e f g ; do
                        ./ip_diff test/$x.txt test/$y.txt > got.txt
                        diff -Naur test/${x}_${y}_diff.txt got.txt
                        rm got.txt
                      done
                    done

  build-1.20:
    <<: *build-template
    docker:
      - image: cimg/go:1.20

  build-1.21:
    <<: *build-template
    docker:
      - image: cimg/go:1.21
